#!/usr/bin/ruby

require 'gtk2'
require 'rubygems'
require 'git'
require 'pp'
require 'time'

include FileUtils

$VERSION = '1.0.1 alpha'

BASE_DIR = File.expand_path(File.dirname(__FILE__))

Dir.glob("#{BASE_DIR}/libs/*.rb").each do |library|
  require library
end

puts "BASE_DIR = #{BASE_DIR}"
$git = Git.init BASE_DIR + '/notes'
puts "Git repo initialized!"

Dir.chdir(BASE_DIR + '/notes')

Gtk.init
$window = Gitruno.new
$window.show_all
Gtk.main
