#!/usr/bin/ruby

require 'gtk2'
require 'rubygems'
require 'git'
require 'pp'
require 'time'

BASE_DIR = File.expand_path(File.dirname(__FILE__))

require BASE_DIR + '/libs/string'
require BASE_DIR + '/libs/gitruno'
require BASE_DIR + '/libs/note'

puts "BASE_DIR = #{BASE_DIR}"
$git = Git.init BASE_DIR + '/notes'
puts "Git repo initialized!"

print "Syncing notes from repo... "

Dir.chdir(BASE_DIR + '/notes')
system("git pull origin master")
print "OK\n"

Gtk.init
$window = Gitruno.new
Gtk.main
