#!/usr/bin/ruby

require 'gtk2'
require 'rubygems'
require 'git'
require 'pp'

BASE_DIR = File.expand_path(File.dirname(__FILE__))

require BASE_DIR + '/libs/string'
require BASE_DIR + '/libs/gitruno'
require BASE_DIR + '/libs/note'

puts "BASE_DIR = #{BASE_DIR}"
$git = Git.init BASE_DIR + '/notes'
puts "Git repo initialized!"
puts ""

Gtk.init
$window = Gitruno.new
Gtk.main
